version: '3.8'
services:
  elasticsearch:
    container_name: elasticsearch-demo
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana-demo
    environment:
      ELASTICSEARCH_URL: http://yourip:9200
      ELASTICSEARCH_HOSTS: http://yourip:9200
    ports:
      - 5601:5601
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.2
    container_name: logstash-demo
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/conf.d/:/usr/share/logstash/pipeline/:ro
    networks:
      - elastic

volumes:
  es-data:
    driver: local

networks:
  elastic:
    driver: bridge